"""Add: slug to user_pages

Revision ID: f92a1f25fd2e
Revises: 7fcc051a54ea
Create Date: 2023-08-28 21:51:27.548071

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f92a1f25fd2e'
down_revision = '7fcc051a54ea'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_pages', sa.Column('slug', sa.String(length=80), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_pages', 'slug')
    # ### end Alembic commands ###
