"""user_projects slug added

Revision ID: 7b8dc83839ca
Revises: 7d7ba2217e75
Create Date: 2023-08-26 23:24:31.737405

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b8dc83839ca'
down_revision = '7d7ba2217e75'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_projects', sa.Column('slug', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_projects', 'slug')
    # ### end Alembic commands ###
